version: '3'
services:
  web:
    image: your-image-name:latest
    build: .
    ports:
      - "80:80"
    environment:
      - ENV=staging
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
